apiVersion: apps/v1
kind: Deployment
metadata: 
  name: petclinic
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      component: petclinic
  template:
    metadata:
      labels:
        component: petclinic
    spec:
      containers:
      - name: petclinic
        image: us-central1-docker.pkg.dev/arc-mark-volfson-sandbox/petclinic-demo/petclinic:v1
        #image: spring-petclinic:k8s
        ports: 
          - containerPort: 8080
        # env:
        #   - name: CONTRAST__APPLICATION__NAME
        #     value: "petclinic-k8s"
        #   - name: CONTRAST__SERVER__NAME
        #     value: "EKS-Core-Pod"
        #   - name: CONTRAST__SERVER__ENVIRONMENT
        #     value: "QA"
        #   - name: CONTRAST_CONFIG_PATH
        #     value: "/etc/contrast/contrast_security.yaml"
        #   - name: AGENT__LOGGER__STDOUT
        #     value: "true"
        #   - name: AGENT__LOGGER__LEVEL
        #     value: "INFO"
        envFrom:
          - configMapRef:
              name: contrast-config
        #Volume Mount for contrast_security.yaml  
        volumeMounts:
        - name: contrast-security
          readOnly: false
          mountPath: "/etc/contrast"
        resources:
          requests:
            cpu: 1.0
            memory: 2Gi
          limits:
            cpu: 2.0
            memory: 4Gi
      # Volume from contrast-security secret     
      volumes:
      - name: contrast-security
        secret:
          secretName: contrast-security