name: Snyk Scan

on:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk scan
        id: snyk-scan
        run: |
          snyk iac test > snyk_report.txt || true

      - name: Read Snyk IaC report file
        id: read-snyk-report
        run: |
          report_contents=$(cat snyk_report.txt)
          echo "::set-output name=report-contents::$report_contents"

      - name: Check Medium Severity Issues
        id: check-medium-issues
        run: |
          number=$(grep -o 'Medium Severity Issues: [0-9]\+' snyk_report.txt | grep -o '[0-9]\+')
          echo "::set-output name=number::$number"
      
      - name: Upload Snyk scan report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk_report.json

      - name: Open Azure DevOps Ticket
        if: steps.check-medium-issues.outputs.number == '3'
        uses: Azure/cli@v1.0.7
        with:
          azcliversion: 'latest'
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az extension add --name azure-devops
            echo ${{ secrets.PAT_AZURE }} | az devops login --organization "https://dev.azure.com/markvolfson/"
            description=$(cat snyk_report.txt)
            az devops configure --defaults organization=https://dev.azure.com/markvolfson/ project=appsec-demo
            az boards work-item create --title "PR Failed - Snyk Results" --type "Task" --description "$description"
        
      - name: Quality Gate
        id: quality-gate
        run: |
          failure("Code contains security vulnerabilities")