name: Snyk Scan

on:
  workflow_dispatch:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk scan
        run: snyk test --all-projects --json > snyk_report.json

      - name: Check Snyk scan results
        run: |
          jq -r '.vulnerabilities | .[] | select(.severity == "high" or .severity == "critical")' snyk_report.json
          if [ $? -eq 0 ]; then
            echo "Critical vulnerabilities found. Exiting..."
            exit 1
          fi

      - name: Upload Snyk scan report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk_report.json
